---
title: "AID Clase 7"
author: "Cecilia Oliva"
date: "1º de junio de 2019"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>
<br>

<center> <h1>Análisis de Correspondencias</h1> </center>

<br>
<br>

### <span style="color:darkred">Ejemplo: datos Titanic</span>
<br>

```{r include=FALSE}
#recordar instalar los paquetes si no están instalados aún
library(ca)
library(FactoMineR)
library(factoextra)
```

```{r echo=TRUE}
#recordar instalar los paquetes si no están instalados aún
#library(ca)
#library(FactoMineR)
#library(factoextra)
```
```{r echo=TRUE}
class(Titanic)

dim(Titanic)

Titanic
```

```{r echo=TRUE}
TitAdulSobrev<-as.data.frame(Titanic[1:4,1,2,])

TitAdulSobrev

df<-data.frame("Survived.Y"=TitAdulSobrev$Freq[5:8],"Survived.N"=TitAdulSobrev$Freq[1:4],"NoData"=c(0,0,2,4))
row.names(df)=TitAdulSobrev$Class[1:4]
df
```
<br>
<br>

### <span style="color:darkred">Gráficos de Perfiles Fila y Columna</span>
<br>
<br>
<h4>Proporción total</h4>
```{r echo=TRUE}
N<-sum(df)
Prop<-df/N
Prop<-round(Prop,4)
Prop
```
<br>
<br>
<h4>Totales Fila</h4>
```{r echo=TRUE}
TotFilas<-apply(df,1,sum)
dfFil<-cbind(df,TotFilas)
colnames(dfFil)[ncol(df)+1]<-"TotFil"
dfFil
```
<br>
<br>
<h4>Perfiles filas</h4>
```{r echo=TRUE}
dfPerFil<-dfFil[,-ncol(dfFil)]/rbind(rep(dfFil[1,ncol(df)+1],ncol(df)),rep(dfFil[2,ncol(df)+1],ncol(df)),rep(dfFil[3,ncol(df)+1],ncol(df)),rep(dfFil[4,ncol(df)+1],ncol(df)))
dfPerFil<-cbind(dfPerFil,apply(dfPerFil,1,sum))
colnames(dfPerFil)[ncol(dfPerFil)]<-"SumaFil"
dfPerFil<-round(dfPerFil,3)
dfPerFil

```
<br>
<br>
<h4>Totales Columna</h4>
```{r echo=TRUE}
TotColumnas<-apply(df,2,sum)
dfCol<-rbind(df,TotColumnas)
rownames(dfCol)[nrow(df)+1]<-"TotCol"
dfCol
```
<br>
<br>
<h4>Perfiles columnas</h4>
```{r echo=TRUE}
dfPerCol<-dfCol[-nrow(dfCol),]/cbind(rep(dfCol[nrow(df)+1,1],nrow(df)),rep(dfCol[nrow(df)+1,2],nrow(df)),rep(dfCol[nrow(df)+1,3],nrow(df)))
dfPerCol<-rbind(dfPerCol,apply(dfPerCol,2,sum))
rownames(dfPerCol)[nrow(dfPerCol)]<-"SumaCol"
dfPerCol<-round(dfPerCol,3)
dfPerCol
```
<br>
<br>
<h4>Totales filas y columnas</h4>
```{r echo=TRUE}
TotFilyCol<-apply(dfFil,2,sum)
dfFilCol<-rbind(dfFil,TotFilyCol)
rownames(dfFilCol)[nrow(dfFil)+1]<-"TotCol"
dfFilCol
```
<br>
<br>
<h4>Proporciones filas y columnas</h4>
```{r echo=TRUE}
N<-sum(df)
PropTot<-dfFilCol/N
PropTot<-round(PropTot,3)
PropTot
```
<br>
<br>
<h4>Perfil medio Filas</h4>
```{r echo=TRUE}
dfPerfilMedioFilas<-dfFilCol[,-ncol(dfFilCol)]/rbind(rep(dfFilCol[1,ncol(dfFilCol)],3),rep(dfFilCol[2,ncol(dfFilCol)],3),rep(dfFilCol[3,ncol(dfFilCol)],3),rep(dfFilCol[4,ncol(dfFilCol)],3),rep(dfFilCol[5,ncol(dfFilCol)],3))
dfPerfilMedioFilas<-round(dfPerfilMedioFilas,3)
rownames(dfPerfilMedioFilas)[5]<-"Perfil Medio"
dfPerfilMedioFilas

plot(1:3,dfPerfilMedioFilas[1,],ylim=c(0,2),type="b",pch=16,xlab="Sobrevivientes",ylab="Proporción",xaxt='n',lwd=2)
mtext("Perfiles Filas",line=0)
axis(1,at=1:3,labels=colnames(dfPerfilMedioFilas))
lines(1:3,dfPerfilMedioFilas[2,],pch=16,type="b",col=2,lwd=2)
lines(1:3,dfPerfilMedioFilas[3,],pch=16,type="b",col=3,lwd=2)
lines(1:3,dfPerfilMedioFilas[4,],pch=16,type="b",col=4,lwd=2)
lines(1:3,dfPerfilMedioFilas[5,],pch=16,type="b",col=5,lwd=2,lty=2)
legend(2.3,2,rownames(dfPerfilMedioFilas),box.lty=0,pch=16,col=1:5,lwd=2,lty=c(1,1,1,1,2),cex=0.85,title="Clase")
```
<br>
<br>
<h4>Perfil medio Columnas</h4>
```{r echo=TRUE}
dfPerfilMedioColumnas<-dfFilCol[-nrow(dfFilCol),]/cbind(rep(dfFilCol[nrow(dfFilCol),1],4),rep(dfFilCol[nrow(dfFilCol),2],4),rep(dfFilCol[nrow(dfFilCol),3],4),rep(dfFilCol[nrow(dfFilCol),4],4))
dfPerfilMedioColumnas<-round(dfPerfilMedioColumnas,3)
colnames(dfPerfilMedioColumnas)[4]<-"Perfil Medio"
dfPerfilMedioColumnas

plot(1:4,dfPerfilMedioColumnas[,1],ylim=c(0,1.5),type="b",pch=16,xlab="Clase",ylab="Proporción",xaxt='n',lwd=2)
mtext("Perfiles Columnas",line=0)
axis(1,at=1:4,labels=rownames(dfPerfilMedioColumnas))
lines(1:4,dfPerfilMedioColumnas[,2],pch=16,type="b",col=2,lwd=2)
lines(1:4,dfPerfilMedioColumnas[,3],pch=16,type="b",col=3,lwd=2)
lines(1:4,dfPerfilMedioColumnas[,4],pch=16,type="b",col=5,lwd=2,lty=2)
legend(3,1.5,colnames(dfPerfilMedioColumnas),box.lty=0,pch=16,col=c(1:3,5),lwd=2,lty=c(1,1,1,2),cex=0.85,title="Sobrevivientes")

```
<br>
<br>

### <span style="color:darkred">Análisis de Correspondencia Simple</span>
<br>

```{r echo=TRUE}
df.ca <- CA(df, graph = FALSE)
ro<-get_ca_row(df.ca) # vemos lo que se guarda de las filas
co<-get_ca_col(df.ca) # vemos lo que se guarda de las columnas

ro$coord
ro$contrib
ro$cos2
ro$inertia

co$coord
co$contrib
co$cos2
co$inertia


fviz_contrib(df.ca, choice = "row", axes = 1) # graficamos las categorías de las filas
fviz_contrib(df.ca, choice = "col", axes = 1) # graficamos las categorías de las columnas
fviz_ca_row(df.ca, repel = TRUE)
fviz_ca_col(df.ca)
fviz_ca_biplot(df.ca, repel = TRUE) 

summary(df.ca)
``` 
<br>
<br>

### <span style="color:darkred">Análisis de Correspondencia Múltiple</span>
<br>

```{r echo=TRUE}
Tit<-as.data.frame(Titanic)

dfmultvars<-data.frame("Class"=NA,"Sex"=NA,"Age"=NA,"Survived"=NA)
dfmultvars<-dfmultvars[-1,]#elimino la única fila que sólo contiene NAs
dfmultvars
```


```{r echo=TRUE}
#Creo esta función para poder armar el input necesario para aplicar el comando MCA
RepeatVecByRows<-function(vec,n){
  new<-vector()
  if(n==0){
    new<-rep(NULL,length(vec))
  }
  if(n!=0){
    for (i in 1:n){
      new<-rbind(new,vec)
    }
  }
  rownames(new)<-NULL
  return(new)
}

#Evalúo la función con un vector cualquiera:
RepeatVecByRows(c("a","b","c"),4)
```


```{r echo=TRUE}

for (i in 1:nrow(Tit)){
  NEWdf<-RepeatVecByRows(Tit[i,1:4],Tit$Freq[i])
  dfmultvars<-rbind(dfmultvars,NEWdf)
}
head(dfmultvars)
sum(Tit$Freq)
dim(dfmultvars)

unique(dfmultvars)
nrow(unique(dfmultvars))# Hay 24 casos distintos
```

```{r echo=TRUE}
tit.mca <- MCA(dfmultvars,quali.sup=1, graph = T)# las variables deben ser introducidas como factores
fviz_contrib(tit.mca, choice ="var", axes = 1)# contribuciones de las variables
fviz_contrib(tit.mca, choice ="ind", axes = 1, top = 5) # contribuciones de los individuos
fviz_mca_var(tit.mca, repel = TRUE)# construye el biplot simétrico

#Los siguientes gráficos no se visualizan bien porque hay muchos datos en la base

#fviz_mca_ind(tit.mca, col.ind = "blue", habillage = dfmultvars$Sex, addEllipses = TRUE, repel =TRUE) + theme_minimal()# señalo sobre el biplot los grupos definidos por el género
#fviz_mca_ind(tit.mca, col.ind = "blue", habillage = dfmultvars$Survived, addEllipses = TRUE, repel= TRUE) + theme_minimal()# señalo sobre el biplot los grupos definidos según si sobrevivieron o no

summary(tit.mca)

resInd<-get_mca_ind(tit.mca)
head(resInd$coord)
head(resInd$cos2)
head(resInd$contrib)

resVar<-get_mca_var(tit.mca)
resVar$coord
resVar$cos2
resVar$contrib

```


```{r include=FALSE}
library("ade4")
library("corrplot")
library("graphics")
library("foreign")
library("anacor")
```
```{r echo=FALSE}
#recordar instalar los paquetes si no están instalados aún
#library("ade4")
#library("corrplot")
#library("graphics")
#library("foreign")
#options(repos = c(CRAN = "http://cran.rstudio.com"))
#install.packages("anacor")
#library("anacor")

```
```{r echo=TRUE}
mat_disy<-acm.disjonctif(dfmultvars)# matriz disyuntiva
head(mat_disy)
burtTable(dfmultvars) # calcula la matriz de Burt
mca.tit <- dudi.acm(dfmultvars, scannf = FALSE)
summary(mca.tit)
round(mca.tit$c1,3) # coordenadas de representación en el biplot


```